@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOiIxOWZlMzllOC04MmVkLTQwZjUtYjkwYi05ZGMyYzdjYzQ1NzUiLCJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIiwicm9sZSI6IlVTRVIifSwiZXhwIjoxNzc5MzY0NzA4fQ.FWHGarvAkGjRoHOELWLgmy9atWlpkUVwnLvnx_IQ2Xg"

GET http://localhost:8000/users/me HTTP/1.1
Authorization: Bearer {{token}}